### ISSUE TITLE
patch for ssh version 1 in macOS Sierra no longer works

### ISSUE THREAD

**Issue by andymadge** [boltomli/MyMacScripts#1]
Running the patch now gives an error.

    $ curl -fsSL https://github.com/boltomli/MyMacScripts/raw/master/homebrew/homebrew-core.openssh.diff | patch /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/openssh.rb
    patching file /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/openssh.rb
    Hunk #1 succeeded at 16 with fuzz 2.
    Hunk #2 succeeded at 36 with fuzz 1 (offset 3 lines).
    Hunk #3 FAILED at 55.
    1 out of 3 hunks FAILED -- saving rejects to file /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/openssh.rb.rej`

Hunk #3 is:

    @@ -44,6 +52,7 @@ class Openssh < Formula
         ]
     
         args << "--with-ldns" if build.with? "ldns"
    +    args << "--with-ssh1" if build.with? "ssh1"
     
         system "./configure", *args
         system "make"

But that area of file `/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/openssh.rb` looks like this so that patch can't be applied:

    system "./configure", "--with-libedit",
                          "--with-kerberos5",
                          "--prefix=#{prefix}",
                          "--sysconfdir=#{etc}/ssh",
                          "--with-pam",
                          "--with-ssl-dir=#{Formula["openssl"].opt_prefix}"
    system "make"

**Comment by boltomli** [comment]
It's related to [upstream commit](https://github.com/Homebrew/homebrew-core/commit/ef4e9ee679e718f00a15089a8da4139281596b12) in which `ldns` is temporarily removed. Given that it's likely to change again soon, I will not update the patch at the moment.

In the meanwhile, please edit the file manually to add ssh1 support to configure arguments. Thanks for raising the issue. I'll leave this open and watch for it closely.

**Comment by nflagey** [comment]
not sure I understand what the fix is ... could you please be more explicit?

**Comment by andymadge** [comment]
If I'm understanding correctly, @boltomli is suggesting that the patch should be applied as normal, but then the failing hunk #3 change needs to be added manually.

That means manually edit file `/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/openssh.rb` and add the single line, `"--with-ssh1" if build.with? "ssh1"` so this:

    system "./configure", "--with-libedit",
                          "--with-kerberos5",
                          "--prefix=#{prefix}",
                          "--sysconfdir=#{etc}/ssh",
                          "--with-pam",
                          "--with-ssl-dir=#{Formula["openssl"].opt_prefix}"
    system "make"
    system "make", "install"

becomes this:

    system "./configure", "--with-libedit",
                          "--with-kerberos5",
                          "--prefix=#{prefix}",
                          "--sysconfdir=#{etc}/ssh",
                          "--with-pam",
                          "--with-ssl-dir=#{Formula["openssl"].opt_prefix}",
                          "--with-ssh1" if build.with? "ssh1"
    system "make"
    system "make", "install"

(don't forget to add the comma at the end of the previous line)

I haven't actually tested it yet though.

**Comment by andymadge** [comment]
Actually reading that back I don't think it will work as I've shown it.  I don't really know Ruby, but I think the original form is a conditional that only adds the line if the ssh1 option is set.

Presumably adding the shortened line `"--with-ssh1"` will work, but it will always include ssh1, regardless of whether that option is set.

That probably doesn't matter here, since a build with ssh1 is exactly what we're trying to achieve, but it feels like it's introducing a potential bug for the future...

Just to clarify, this is what I'm proposing, and I think it will work, but I don't really like it:

    system "./configure", "--with-libedit",
                          "--with-kerberos5",
                          "--prefix=#{prefix}",
                          "--sysconfdir=#{etc}/ssh",
                          "--with-pam",
                          "--with-ssl-dir=#{Formula["openssl"].opt_prefix}",
                          "--with-ssh1"
    system "make"
    system "make", "install"

**Comment by boltomli** [comment]
Thanks Andy, I think it works. In fact I don't know Ruby either. And I almost share the same feeling with you :)

**Comment by andymadge** [comment]
Would it be worth adding this to your repo in a separate branch so there's a workaround until upstream adds back ldns?

I'm happy to do a pull request if you want me to.

**Comment by boltomli** [comment]
It would be great! Thanks!

**Comment by andymadge** [comment]
Ok sure I'll do it as soon as I have time to test it.

**Comment by boltomli** [comment]
It might be resolved by commit d951186fdae3620b5e7631526b0fe3d9ba9a6ed5 but it will be as is forever since it's dropped in openssh.
